
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjBjNTMyZTQyZTdmYmMyY2UwNzgyNDRiIn0sImlhdCI6MTYyNDIxOTE0NSwiZXhwIjoxNjI0MjI2MzQ1fQ.rTcSxYqj2sVj0O8X-bziHhNl5FXMFAIrUjnUAB4nFH4


### Listar maestros
GET http://localhost:4000/api/teachers


### Agregar maestro
POST http://localhost:4000/api/teachers
Content-Type: application/json

{
    "nombre": "Abel Romero Ruiz",
    "nombramiento": "Jefe",
    "sexo":"M",
    "ingreso_institucion": "2002-12-09",
    "atiguedad": "2002-12-09",
    "grado_max": "Licenciatura"
}

### Buscar un maestro
GET http://localhost:4000/api/teachers/60809ca01d0bc52a6efe7a95

#------------------------------------------------------------------------------------------

#### Iniciar Sesión
POST http://localhost:4000/api/auth
Content-Type: application/json

{
    "email": "abel@gmail.com",
    "password": "123456"
}
### Usuario obtener
GET  http://localhost:4000/api/auth
Authorization: {{token}}

#------------------------------------------------------------------------------------------

### Listar carreras
GET http://localhost:4000/api/career


### Agregar carrera
POST http://localhost:4000/api/careers
Content-Type: application/json
Authorization: {{token}}

{
    "nombre": "Ingeneria"
}

### Buscar un maestro
GET http://localhost:4000/api/teachers/60809ca01d0bc52a6efe7a95

#------------------------------------------------------------------------------------------
